### ISSUE TITLE
Toggle does not work correctly in web 

### ISSUE THREAD

**Issue by HeySlava** [HeySlava/pomodoro#5]
When a process is paused, the app fetches data and decreases seconds

<img width="475" alt="изображение" src="https://github.com/HeySlava/pomodoro/assets/69298864/44d6323d-0124-44e7-920e-a449f91edae9">

**Comment by lavrov-webdev** [comment]
@HeySlava 
А time_left, которое приходит с сервера, в случае паузы не продолжает уменьшаться?

**Comment by HeySlava** [comment]
@lavrov-webdev you are right. I will fix it

https://github.com/HeySlava/pomodoro/blob/main/app/api/pomodoro/main.py#L34-L36
